<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Drop-in OpenTelemetry configuration for ASP.NET Core applications.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>TelemetryBridge.AspNetCore</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TelemetryBridge.Core/TelemetryBridge.Core.csproj" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Process" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
