services:
  otel-agent:
    image: otel/opentelemetry-collector-contrib:0.153.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./collector/tail-sampling/agent.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "14317:4317"
      - "14318:4318"
    depends_on:
      - tail-sampler-1
      - tail-sampler-2

  tail-sampler-1:
    image: otel/opentelemetry-collector-contrib:0.153.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./collector/tail-sampling/decision.yaml:/etc/otelcol/config.yaml:ro
    depends_on:
      - tempo

  tail-sampler-2:
    image: otel/opentelemetry-collector-contrib:0.153.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./collector/tail-sampling/decision.yaml:/etc/otelcol/config.yaml:ro
    depends_on:
      - tempo

  internal-api:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-agent:4317
  legacy-api:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-agent:4317
  modern-api:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-agent:4317
  worker:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-agent:4317
  facade:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-agent:4317
  admin-api:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-agent:4317
