<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/TelemetryBridge.Core/TelemetryBridge.Core.csproj" />
    <ProjectReference Include="../../src/TelemetryBridge.AspNetCore/TelemetryBridge.AspNetCore.csproj" />
    <ProjectReference Include="../../src/TelemetryBridge.NLog/TelemetryBridge.NLog.csproj" />
    <ProjectReference Include="../../src/TelemetryBridge.StranglerFacade/TelemetryBridge.StranglerFacade.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
